dodamdodam/dodam/urls.py
from dodam import views
from django.urls import path
#TEMPLATE TAGGING
app_name = 'dodam_app'

urlpatterns= [
    path('last<str:id>',views.last,name='last'),
    path('mypage/',views.mypage,name='mypage'),
    path('picture<str:id>',views.picture,name='picture'),
    path('voice<str:id>',views.voice,name='voice'),
    path('consult/', views.consult,name='consult'),
    path('setquest/', views.setquest,name='setquest'),
    path('join/',views.join,name='join'),
    path('home/',views.home,name="home"),
    path('result<str:id>', views.result,name='result'),
    path('diary<str:id>', views.diary, name="diary"),
    path("record<str:id>", views.record, name="record"),
    path("login/", views.login, name="login"),
    path("nextVoice<str:id>", views.nextVoice, name="nextVoice"),
    path("finalVoice<str:id>", views.finalVoice, name="finalVoice"),
]

dodamdodam/dodamdodam/urls.py
from django.contrib import admin
from django.urls import path
from dodam import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name='login'),
    path('dodam/',include('dodam.urls')),
    path('setQ/', views.setQ, name='setQ'),
    path('drawing/', views.drawing, name='drawing'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dodamdodam/dodam/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class answer(models.Model):
    pub_date = models.DateTimeField('data published')
    q1 = models.CharField(max_length=200)
    q2 = models.CharField(max_length=200)
    q3 = models.CharField(max_length=200)
    picture = models.CharField(max_length=100)
    ans = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.writer)+" : "+str(self.pub_date)
        
class Picture(models.Model):
    draw = models.ImageField(blank=True, upload_to="images", null=True)

dodamdodam/dodam/views.py
from django.http import request
from django.shortcuts import redirect, render, get_object_or_404
from .models import answer
from .models import Picture

# from .static.stt import main
# from .static.tts import run_quickstart, play

from django.contrib.auth.models import User
from django.contrib import auth
from django.utils import timezone
# Create your views here.

def home(request):
    return render(request, 'home.html')

def last(request, id):
    take = get_object_or_404(answer,pk=id)
    return render(request, 'last.html',{'take':take})

def mypage(request):
    return render(request, 'mypage.html')

def picture(request, id):
    take = get_object_or_404(answer,pk=id)
    return render(request, 'picture.html', {'take':take})

def voice(request,id):
    take = get_object_or_404(answer,pk=id)
    return render(request, 'voice.html',{'take':take, 'state':'next'})

def consult(request):
    return render(request, 'consult.html')

def setquest(request):
    return render(request, "setquest.html")

def join(request):
    if request.method == "POST":
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                request.POST["username"], password=request.POST["password1"]
            )
            # auth.login(request, user)
            return redirect("/dodam/login/")  # 뭐넣어야하는지 고민해보자
    return render(request, "join.html")

def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect("/dodam/consult/")
        else:
            return render(
                request, "login.html", {"error": "username or password is incorrect"}
            )
    else:
        return render(request, "login.html")

def result(request, id):
    take = get_object_or_404(answer,pk=id)
    return render(request, 'result.html', {'take':take})

def setQ(request):
    if(request.method == 'POST'):
        take = answer()
        take.pub_date = timezone.datetime.now()
        take.q1 = "오늘은 기분이 어때? 왜 그런 기분이야?"
        if request.POST["ans1"]:
            take.q1 = request.POST["ans1"]
        take.q2 = "오늘 기뻤던 일은 뭐야?"
        if request.POST["ans2"]:
            take.q2 = request.POST["ans2"]
        take.q3 = "오늘 슬펐던 일은 뭐야?"
        if request.POST["ans3"]:
            take.q3 = request.POST["ans3"]
        take.picture = "집"
        if request.POST["ans4"]:
            take.picture = request.POST["ans4"]
        take.writer = request.user
        take.save()
    return render(request, "home.html", {'take':take})

def picture(request,id):
    take = get_object_or_404(answer,pk=id)
    return render(request, 'picture.html', {'take': take})

def diary(request, id):
    take = get_object_or_404(answer,pk=id)
    return render(request, "diary.html", {'take': take})

def record(request,id):
    take = get_object_or_404(answer,pk=id)
    # run_quickstart(take.q1, take.q2, take.q3) #TTS
    # play("output.mp3",True)
    # take.ans = main() #STT
    take.save()
    return render(request, "voice.html",{'take':take})

def nextVoice(request,id):
    take = get_object_or_404(answer,pk=id)
    # play("output2.mp3",False)
    return render(request, "voice.html",{'take':take, 'state':'final'})

def finalVoice(request,id):
    take = get_object_or_404(answer,pk=id)
    # play("output3.mp3",False)
    return render(request, "voice.html",{'take':take})

def drawing(request):
    draw = Picture('imgBase64')
    draw.draw = request.POST['imgBase64']
    draw.save()
    return redirect("/dodam/result/")

dodamdodam/dodam/templates/consult.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{%static 'consult.css' %}">
    <title>도담도담</title>
    <style>
        @font-face {
        font-family: 'SeoulNamsanM';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }
    </style>
</head>
<body>
    
    <div class="box"></div>

    <p class="mention1">상담 시작 전</p><br><br>

    <p class="mention2">안녕하세요<br>
        아이와의 소중한 시간을 위해<br>
        도담도담을 선택해 주셔서 감사합니다.<br><br>
        아이의 솔직한 속마음을 알기 위한<br>
        질문을 직접 입력할 수 있습니다!</p>

    <a href="{% url 'dodam_app:setquest' %}"><button id="check">입력하기</button></a>

</body>
</html>

dodamdodam/dodam/templates/diary.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{%static 'diary.css' %}" />
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
    <title>도담도담</title>
  </head>
  <style>
    @font-face {
      font-family: "SeoulNamsanM";
      src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff")
        format("woff");
      font-weight: normal;
      font-style: normal;
    }
  </style>
  <body>
    <div class="dragmelist">
      <div id="draggable"></div>
      <img
        src="{%static 'sun.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'snow.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'raining.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'windy.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'fastfd.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'ramen.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'pizza.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />
      <br /><br />
      <div id="draggable"></div>
      <img
        src="{%static 'smile.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'sad.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'surprised.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'angry.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'chicken.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'block.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'robot.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />
      <br /><br />
      <div id="draggable"></div>
      <img
        src="{%static 'friendship (1).png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'friendship.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'family.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'play-with-pet.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'bear.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'cow.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />&nbsp;&nbsp;&nbsp;&nbsp;
      <img
        src="{%static 'horse.png' %}"
        alt="drag-and-drop image script"
        title="drag-and-drop image script"
        class="dragme"
      />
    </div>
    <div>
      <img src="{%static 'cocomong.png' %}" alt="coco" class="cocomong" />
    </div>
    <div>
      <!-- <img src="{%static 'text.png' %}" alt="text"  class="text"> -->
      <p class="mention1">Step 2.</p>
      <p class="mention2">이모티콘으로 오늘 하루를 표현해주세요!</p>
    </div>
    <a href="{% url 'dodam_app:home' %}"
      ><button id="before">이전단계</button></a
    >
    <a href="{% url 'dodam_app:picture' take.id %}"
      ><button id="next">다음단계</button></a
    >
    <div>
      <img src="{%static 'Dscreen.PNG' %}" alt="Dscreen" class="DS" />
    </div>

    <button id="shot">일기를 다 썼으면<br>나를 눌러 줘!</button>
    <script src="{%static 'move.js' %}" type="text/javascript"></script>
  </body>
</html>

dodamdodam/dodam/templates/home.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="UTF-8" />
    <title>도담도담</title>
    <link rel="stylesheet" href="{%static 'home.css' %}" />
  </head>

  <body>
    <img src="{%static '도담도담.png' %}" class="dodo" alt="도담도담" />
    <a href="{% url 'dodam_app:voice' take.id %}"
      ><img src="{%static '시작하기.png' %}" class="start" alt="시작하기"
    /></a>
  </body>
</html>

dodamdodam/dodam/templates/index.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="UTF-8" />
    <title>도담도담</title>
    <link rel="stylesheet" href="{%static 'login.css' %}" />
    <style>
      @font-face {
        font-family: "SeoulNamsanM";
        src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff")
          format("woff");
        font-weight: normal;
        font-style: normal;
      }
    </style>
  </head>

  <body>
    <img src="{%static '도담도담.png' %}" class="dodo" alt="도담도담" />

    {% if error %} {{ error }} {% endif %}
    <form method="POST" action="{% url 'dodam_app:login' %}">
      {% csrf_token %}
      <!-- username: -->
      <input
        name="username"
        type="text"
        value=""
        id="idbox"
        placeholder="    아이디"
      />
      <br />
      <!-- Password: -->
      <br />
      <input
        name="password"
        type="password"
        value=""
        id="pwbox"
        placeholder="    패스워드"
      />
      <br />
      <br />
      <input name="button" type="submit" value="login" id="check" />
    </form>
    <a href="{% url 'dodam_app:join' %}"><button id="subt">회원가입</button></a>
  </body>
</html>

dodamdodam/dodam/templates/join.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>도담도담</title>
    <link rel="stylesheet" href="{%static 'join.css' %}">
    <style>
        @font-face {
            font-family: 'SeoulNamsanM';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }
    </style>
</head>

<body>

    <div class="box"></div>

    <p class="mention1">회원가입</p>

    <div class="line"></div>

    <div class="back"></div>

    <button id="box1">프로필 사진</button>
    <button id="box2">사용자ID</button>
    <button id="box3">비밀번호</button>
    <button id="box4">비밀번호 재확인</button>
    <button id="box5">보호자 이름</button>
    <button id="box6">아이 이름</button>
    <button id="box7">아이 생년월일</button>
    <button id="box8">이메일</button>

    <!-- <input type="text" name="write2" id="write2">
    <input type="text" name="write3" id="write3">
    <input type="text" name="write4" id="write4">
    <input type="text" name="write5" id="write5">
    <input type="text" name="write6" id="write6">
    <input type="text" name="write7" id="write7">
    <input type="text" name="write8" id="write8">

    <a href="{% url 'login' %}"><button id="check">회원가입완료</button></a> -->

    <form method="POST" action="{% url 'dodam_app:join' %}">
        {% csrf_token %}
        <!-- username: -->
        <br>
        <input name="username" type="text" value="" id="write2" placeholder="    사용자 ID를 입력해주세요."> 
        <br>
        <!-- Password: -->
        <br>
        <input name="password1" type="password1" value="" id="write3" placeholder="    사용자 PASSWORD를 입력해주세요.">
        <br>
        <!-- Confirm Password: -->
        <br>
        <input name="password2" type="password2" value="" id="write4" placeholder="    사용자 PASSWORD를 한번 더 입력해주세요.">
        <br>
        <!-- guardian name: -->
        <br>
        <input name="guardian name" type="text" value="" id="write5" placeholder="    보호자 이름을 입력해주세요.">
        <br>
        <!-- child name: -->
        <br>
        <input name="child name" type="text" value="" id="write6" placeholder="    아이 이름을 입력해주세요.">
        <br>
        <!-- birth date: -->
        <br>
        <input name="birth date" type="text" value="" id="write7" placeholder="    아이의 생년월일을 입력해주세요. (YYYY-MM-DD)">
        <br>
        <!-- email: -->
        <br>
        <input name="email" type="text" value="" id="write8" placeholder="    보호자의 이메일을 입력해주세요.">
        <br>
        
        
        <input name="button" type="submit" value="회원가입 완료" id="check">

        

    </form>

    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="profile"
        viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
        <path
            d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1v-1c0-1-1-4-6-4s-6 3-6 4v1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12z" />
    </svg>

    <button id="image">사진등록 및 변경</button>

</body>

</html>

dodamdodam/dodam/templates/last.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{%static 'last.css' %}">
    <title>도담도담</title>
    <style>
        @font-face {
        font-family: 'SeoulNamsanM';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff') format('woff');
        font-weight: normal;
        font-style: normal;

    }
    </style>
</head>
<body>
    <img src="{% static '코코몽.png' %}" alt="코코몽" class="lastmong">

    <div class="box"></div>
    <p class="mention1">코코몽과의 대화가 끝이 났어요! </p><br>
    <p class="mention2">다음에 또 만나요 :)<br><br>
        코코몽이 집에 가기 위해서<br>
        부모님을 불러 주세요!</p>
    <a href="{% url 'dodam_app:result' take.id %}"><button id="check">결과 확인</button></a>
    </table>

</body>
</html>

dodamdodam/dodam/templates/login.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="UTF-8" />
    <title>도담도담</title>
    <link rel="stylesheet" href="{%static 'login.css' %}" />
    <style>
      @font-face {
        font-family: "SeoulNamsanM";
        src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff")
          format("woff");
        font-weight: normal;
        font-style: normal;
      }
    </style>
  </head>

  <body>
    <img src="{%static '도담도담.png' %}" class="dodo" alt="도담도담" />

    {% if error %} {{ error }} {% endif %}
    <form method="POST" action="{% url 'dodam_app:login' %}">
      {% csrf_token %}
      <!-- username: -->
      <input
        name="username"
        type="text"
        value=""
        id="idbox"
        placeholder="    아이디"
      />
      <br />
      <!-- Password: -->
      <br />
      <input
        name="password"
        type="password"
        value=""
        id="pwbox"
        placeholder="    패스워드"
      />
      <br />
      <br />
      <input name="button" type="submit" value="login" id="check" />
    </form>
    <a href="{% url 'dodam_app:join' %}"><button id="subt">회원가입</button></a>
  </body>
</html>

dodamdodam/dodam/templates/picture.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{%static 'picture.css' %}" />
    <title>도담도담</title>
    <style>
      @font-face {
        font-family: "SeoulNamsanM";
        src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff")
          format("woff");
        font-weight: normal;
        font-style: normal;
      }
    </style>
  </head>
  <body>
    <img src="{%static '코코몽.png' %}" alt="코코몽" class="mong" />
    <p class="mention1">Step 3.</p>
    <p class="mention2">{{take.picture}} 그림을 그려줘!</p>
    <a href="{% url 'dodam_app:home' %}"
      ><button id="before">이전단계</button></a
    >
    <a href="{% url 'dodam_app:last' take.id %}"
      ><button id="next">다음단계</button></a
    >

    <canvas id="jsCanvas" class="canvas"></canvas>
    <div class="controls">
      <div class="controls__range">
        <input
          type="range"
          id="jsRange"
          min="0.1"
          max="5"
          value="2.5"
          step="0.1"
        />
      </div>
      <div class="controls__btns">
        <button id="jsMode">채우기</button>
        <form
          action="{% url 'drawing' %}"
          enctype="multipart/form-data"
          method="POST"
        >
          <button type="button" id="jsSave">그림이 완성됐으면<br>여기를 눌러 줘!</button>
        </form>
      </div>
      <div class="controls__colors" id="jsColors">
        <div
          class="controls__color jsColor"
          style="background-color: #2c2c2c"
        ></div>
        <div
          class="controls__color jsColor"
          style="background-color: white"
        ></div>
        <div
          class="controls__color jsColor"
          style="background-color: #ff3b30"
        ></div>
        <div
          class="controls__color jsColor"
          style="background-color: #ff9500"
        ></div>
        <div
          class="controls__color jsColor"
          style="background-color: #ffcc00"
        ></div>
        <div
          class="controls__color jsColor"
          style="background-color: #4cd963"
        ></div>
        <div
          class="controls__color jsColor"
          style="background-color: #5ac8fa"
        ></div>
        <div
          class="controls__color jsColor"
          style="background-color: #0579ff"
        ></div>
        <div
          class="controls__color jsColor"
          style="background-color: #5856d6"
        ></div>
      </div>
    </div>
    <script src="{%static 'app.js' %}" type="text/javascript"></script>
  </body>
</html>

dodamdodam/dodam/templates/result.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="UTF-8" />
    <title>도담도담</title>
    <link rel="stylesheet" href="{%static 'result.css' %}" />
    <style>
      @font-face {
        font-family: "SeoulNamsanM";
        src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff")
          format("woff");
        font-weight: normal;
        font-style: normal;
      }
    </style>
  </head>

  <body>
    <div id="title">아이와 도담이의 대화</div>
    <a href="{% url 'dodam_app:consult' %}"
      ><button id="home">상담설정</button></a
    >
    <a href="{% url 'dodam_app:mypage' %}"
      ><button id="mypage">MyPage</button></a
    >
    <div id="talk">{{take.ans}}</div>
    <div id="diary"></div>
    <div id="picture">
      <img src="{post.picture.url}" style="width: 100px; height: 100px" />
    </div>
  </body>
</html>

dodamdodam/dodam/templates/voice.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{%static 'voice.css' %}">
    <title>도담도담</title>
    <style>
        @font-face {
        font-family: 'SeoulNamsanM';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff') format('woff');
        font-weight: normal;
        font-style: normal;
        }
    </style>
</head>

<body>
  <img src="{%static '코코몽.png' %}" class="mong">

  <a href="{% url 'dodam_app:home' %}"><button id="before">이전단계</button></a>

  {% if state == "next" %}
  <a href="{% url 'dodam_app:nextVoice' take.id %}"><button id="next">다음단계</button></a>
  {% elif state == "final"%}
  <a href="{% url 'dodam_app:finalVoice' take.id %}"><button id="next">다음단계</button></a>
  {% else %}
  <a href="{% url 'dodam_app:diary' take.id %}"><button id="next">다음단계</button></a>
  {% endif %}

  <p class="mention1">Step 1.</p>
  <p class="mention2">코코몽과 대화해주세요!</p>

  <form action="{% url 'dodam_app:record' take.id %}" method="post">
    {% csrf_token %}
    <button id="sound" type="submit" name="record"></button>
  </form>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="sound" viewBox="0 0 16 16">
    <path
      d="M11.536 14.01A8.473 8.473 0 0 0 14.026 8a8.473 8.473 0 0 0-2.49-6.01l-.708.707A7.476 7.476 0 0 1 13.025 8c0 2.071-.84 3.946-2.197 5.303l.708.707z" />
    <path
      d="M10.121 12.596A6.48 6.48 0 0 0 12.025 8a6.48 6.48 0 0 0-1.904-4.596l-.707.707A5.483 5.483 0 0 1 11.025 8a5.483 5.483 0 0 1-1.61 3.89l.706.706z" />
    <path
      d="M8.707 11.182A4.486 4.486 0 0 0 10.025 8a4.486 4.486 0 0 0-1.318-3.182L8 5.525A3.489 3.489 0 0 1 9.025 8 3.49 3.49 0 0 1 8 10.475l.707.707zM6.717 3.55A.5.5 0 0 1 7 4v8a.5.5 0 0 1-.812.39L3.825 10.5H1.5A.5.5 0 0 1 1 10V6a.5.5 0 0 1 .5-.5h2.325l2.363-1.89a.5.5 0 0 1 .529-.06z" />
  </svg>

  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="mike" viewBox="0 0 16 16">
    <path d="M5 3a3 3 0 0 1 6 0v5a3 3 0 0 1-6 0V3z" />
    <path
      d="M3.5 6.5A.5.5 0 0 1 4 7v1a4 4 0 0 0 8 0V7a.5.5 0 0 1 1 0v1a5 5 0 0 1-4.5 4.975V15h3a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1h3v-2.025A5 5 0 0 1 3 8V7a.5.5 0 0 1 .5-.5z" />
  </svg>
  <p class="listen">듣는 중..</p>

  <rect class="box" alt="사각형">
    <p class="mention">
      아이가 자유롭게<br>
      도담이와 대화를 나눌 수 있게<br>
      자리를 피해주세요.</p>

</body>

</html>